-- Generated from NPPES *_fileheader.csv files (January 2026 bundle).
-- Staging tables intentionally use text for all columns for resilient raw ingestion.
-- Cast to typed analytics tables in downstream transformation SQL.

create schema if not exists nppes;

drop table if exists nppes.stg_nppes_npidata;
create table nppes.stg_nppes_npidata (
    npi text, -- "NPI"
    entity_type_code text, -- "Entity Type Code"
    replacement_npi text, -- "Replacement NPI"
    employer_identification_number_ein text, -- "Employer Identification Number (EIN)"
    provider_organization_name_legal_business_name text, -- "Provider Organization Name (Legal Business Name)"
    provider_last_name_legal_name text, -- "Provider Last Name (Legal Name)"
    provider_first_name text, -- "Provider First Name"
    provider_middle_name text, -- "Provider Middle Name"
    provider_name_prefix_text text, -- "Provider Name Prefix Text"
    provider_name_suffix_text text, -- "Provider Name Suffix Text"
    provider_credential_text text, -- "Provider Credential Text"
    provider_other_organization_name text, -- "Provider Other Organization Name"
    provider_other_organization_name_type_code text, -- "Provider Other Organization Name Type Code"
    provider_other_last_name text, -- "Provider Other Last Name"
    provider_other_first_name text, -- "Provider Other First Name"
    provider_other_middle_name text, -- "Provider Other Middle Name"
    provider_other_name_prefix_text text, -- "Provider Other Name Prefix Text"
    provider_other_name_suffix_text text, -- "Provider Other Name Suffix Text"
    provider_other_credential_text text, -- "Provider Other Credential Text"
    provider_other_last_name_type_code text, -- "Provider Other Last Name Type Code"
    provider_first_line_business_mailing_address text, -- "Provider First Line Business Mailing Address"
    provider_second_line_business_mailing_address text, -- "Provider Second Line Business Mailing Address"
    provider_business_mailing_address_city_name text, -- "Provider Business Mailing Address City Name"
    provider_business_mailing_address_state_name text, -- "Provider Business Mailing Address State Name"
    provider_business_mailing_address_postal_code text, -- "Provider Business Mailing Address Postal Code"
    provider_business_mailing_address_country_code_if_outside_u_s text, -- "Provider Business Mailing Address Country Code (If outside U.S.)"
    provider_business_mailing_address_telephone_number text, -- "Provider Business Mailing Address Telephone Number"
    provider_business_mailing_address_fax_number text, -- "Provider Business Mailing Address Fax Number"
    provider_first_line_business_practice_location_address text, -- "Provider First Line Business Practice Location Address"
    provider_second_line_business_practice_location_address text, -- "Provider Second Line Business Practice Location Address"
    provider_business_practice_location_address_city_name text, -- "Provider Business Practice Location Address City Name"
    provider_business_practice_location_address_state_name text, -- "Provider Business Practice Location Address State Name"
    provider_business_practice_location_address_postal_code text, -- "Provider Business Practice Location Address Postal Code"
    provider_business_practice_location_address_country_code_if_outside_u_s text, -- "Provider Business Practice Location Address Country Code (If outside U.S.)"
    provider_business_practice_location_address_telephone_number text, -- "Provider Business Practice Location Address Telephone Number"
    provider_business_practice_location_address_fax_number text, -- "Provider Business Practice Location Address Fax Number"
    provider_enumeration_date text, -- "Provider Enumeration Date"
    last_update_date text, -- "Last Update Date"
    npi_deactivation_reason_code text, -- "NPI Deactivation Reason Code"
    npi_deactivation_date text, -- "NPI Deactivation Date"
    npi_reactivation_date text, -- "NPI Reactivation Date"
    provider_sex_code text, -- "Provider Sex Code"
    authorized_official_last_name text, -- "Authorized Official Last Name"
    authorized_official_first_name text, -- "Authorized Official First Name"
    authorized_official_middle_name text, -- "Authorized Official Middle Name"
    authorized_official_title_or_position text, -- "Authorized Official Title or Position"
    authorized_official_telephone_number text, -- "Authorized Official Telephone Number"
    healthcare_provider_taxonomy_code_1 text, -- "Healthcare Provider Taxonomy Code_1"
    provider_license_number_1 text, -- "Provider License Number_1"
    provider_license_number_state_code_1 text, -- "Provider License Number State Code_1"
    healthcare_provider_primary_taxonomy_switch_1 text, -- "Healthcare Provider Primary Taxonomy Switch_1"
    healthcare_provider_taxonomy_code_2 text, -- "Healthcare Provider Taxonomy Code_2"
    provider_license_number_2 text, -- "Provider License Number_2"
    provider_license_number_state_code_2 text, -- "Provider License Number State Code_2"
    healthcare_provider_primary_taxonomy_switch_2 text, -- "Healthcare Provider Primary Taxonomy Switch_2"
    healthcare_provider_taxonomy_code_3 text, -- "Healthcare Provider Taxonomy Code_3"
    provider_license_number_3 text, -- "Provider License Number_3"
    provider_license_number_state_code_3 text, -- "Provider License Number State Code_3"
    healthcare_provider_primary_taxonomy_switch_3 text, -- "Healthcare Provider Primary Taxonomy Switch_3"
    healthcare_provider_taxonomy_code_4 text, -- "Healthcare Provider Taxonomy Code_4"
    provider_license_number_4 text, -- "Provider License Number_4"
    provider_license_number_state_code_4 text, -- "Provider License Number State Code_4"
    healthcare_provider_primary_taxonomy_switch_4 text, -- "Healthcare Provider Primary Taxonomy Switch_4"
    healthcare_provider_taxonomy_code_5 text, -- "Healthcare Provider Taxonomy Code_5"
    provider_license_number_5 text, -- "Provider License Number_5"
    provider_license_number_state_code_5 text, -- "Provider License Number State Code_5"
    healthcare_provider_primary_taxonomy_switch_5 text, -- "Healthcare Provider Primary Taxonomy Switch_5"
    healthcare_provider_taxonomy_code_6 text, -- "Healthcare Provider Taxonomy Code_6"
    provider_license_number_6 text, -- "Provider License Number_6"
    provider_license_number_state_code_6 text, -- "Provider License Number State Code_6"
    healthcare_provider_primary_taxonomy_switch_6 text, -- "Healthcare Provider Primary Taxonomy Switch_6"
    healthcare_provider_taxonomy_code_7 text, -- "Healthcare Provider Taxonomy Code_7"
    provider_license_number_7 text, -- "Provider License Number_7"
    provider_license_number_state_code_7 text, -- "Provider License Number State Code_7"
    healthcare_provider_primary_taxonomy_switch_7 text, -- "Healthcare Provider Primary Taxonomy Switch_7"
    healthcare_provider_taxonomy_code_8 text, -- "Healthcare Provider Taxonomy Code_8"
    provider_license_number_8 text, -- "Provider License Number_8"
    provider_license_number_state_code_8 text, -- "Provider License Number State Code_8"
    healthcare_provider_primary_taxonomy_switch_8 text, -- "Healthcare Provider Primary Taxonomy Switch_8"
    healthcare_provider_taxonomy_code_9 text, -- "Healthcare Provider Taxonomy Code_9"
    provider_license_number_9 text, -- "Provider License Number_9"
    provider_license_number_state_code_9 text, -- "Provider License Number State Code_9"
    healthcare_provider_primary_taxonomy_switch_9 text, -- "Healthcare Provider Primary Taxonomy Switch_9"
    healthcare_provider_taxonomy_code_10 text, -- "Healthcare Provider Taxonomy Code_10"
    provider_license_number_10 text, -- "Provider License Number_10"
    provider_license_number_state_code_10 text, -- "Provider License Number State Code_10"
    healthcare_provider_primary_taxonomy_switch_10 text, -- "Healthcare Provider Primary Taxonomy Switch_10"
    healthcare_provider_taxonomy_code_11 text, -- "Healthcare Provider Taxonomy Code_11"
    provider_license_number_11 text, -- "Provider License Number_11"
    provider_license_number_state_code_11 text, -- "Provider License Number State Code_11"
    healthcare_provider_primary_taxonomy_switch_11 text, -- "Healthcare Provider Primary Taxonomy Switch_11"
    healthcare_provider_taxonomy_code_12 text, -- "Healthcare Provider Taxonomy Code_12"
    provider_license_number_12 text, -- "Provider License Number_12"
    provider_license_number_state_code_12 text, -- "Provider License Number State Code_12"
    healthcare_provider_primary_taxonomy_switch_12 text, -- "Healthcare Provider Primary Taxonomy Switch_12"
    healthcare_provider_taxonomy_code_13 text, -- "Healthcare Provider Taxonomy Code_13"
    provider_license_number_13 text, -- "Provider License Number_13"
    provider_license_number_state_code_13 text, -- "Provider License Number State Code_13"
    healthcare_provider_primary_taxonomy_switch_13 text, -- "Healthcare Provider Primary Taxonomy Switch_13"
    healthcare_provider_taxonomy_code_14 text, -- "Healthcare Provider Taxonomy Code_14"
    provider_license_number_14 text, -- "Provider License Number_14"
    provider_license_number_state_code_14 text, -- "Provider License Number State Code_14"
    healthcare_provider_primary_taxonomy_switch_14 text, -- "Healthcare Provider Primary Taxonomy Switch_14"
    healthcare_provider_taxonomy_code_15 text, -- "Healthcare Provider Taxonomy Code_15"
    provider_license_number_15 text, -- "Provider License Number_15"
    provider_license_number_state_code_15 text, -- "Provider License Number State Code_15"
    healthcare_provider_primary_taxonomy_switch_15 text, -- "Healthcare Provider Primary Taxonomy Switch_15"
    other_provider_identifier_1 text, -- "Other Provider Identifier_1"
    other_provider_identifier_type_code_1 text, -- "Other Provider Identifier Type Code_1"
    other_provider_identifier_state_1 text, -- "Other Provider Identifier State_1"
    other_provider_identifier_issuer_1 text, -- "Other Provider Identifier Issuer_1"
    other_provider_identifier_2 text, -- "Other Provider Identifier_2"
    other_provider_identifier_type_code_2 text, -- "Other Provider Identifier Type Code_2"
    other_provider_identifier_state_2 text, -- "Other Provider Identifier State_2"
    other_provider_identifier_issuer_2 text, -- "Other Provider Identifier Issuer_2"
    other_provider_identifier_3 text, -- "Other Provider Identifier_3"
    other_provider_identifier_type_code_3 text, -- "Other Provider Identifier Type Code_3"
    other_provider_identifier_state_3 text, -- "Other Provider Identifier State_3"
    other_provider_identifier_issuer_3 text, -- "Other Provider Identifier Issuer_3"
    other_provider_identifier_4 text, -- "Other Provider Identifier_4"
    other_provider_identifier_type_code_4 text, -- "Other Provider Identifier Type Code_4"
    other_provider_identifier_state_4 text, -- "Other Provider Identifier State_4"
    other_provider_identifier_issuer_4 text, -- "Other Provider Identifier Issuer_4"
    other_provider_identifier_5 text, -- "Other Provider Identifier_5"
    other_provider_identifier_type_code_5 text, -- "Other Provider Identifier Type Code_5"
    other_provider_identifier_state_5 text, -- "Other Provider Identifier State_5"
    other_provider_identifier_issuer_5 text, -- "Other Provider Identifier Issuer_5"
    other_provider_identifier_6 text, -- "Other Provider Identifier_6"
    other_provider_identifier_type_code_6 text, -- "Other Provider Identifier Type Code_6"
    other_provider_identifier_state_6 text, -- "Other Provider Identifier State_6"
    other_provider_identifier_issuer_6 text, -- "Other Provider Identifier Issuer_6"
    other_provider_identifier_7 text, -- "Other Provider Identifier_7"
    other_provider_identifier_type_code_7 text, -- "Other Provider Identifier Type Code_7"
    other_provider_identifier_state_7 text, -- "Other Provider Identifier State_7"
    other_provider_identifier_issuer_7 text, -- "Other Provider Identifier Issuer_7"
    other_provider_identifier_8 text, -- "Other Provider Identifier_8"
    other_provider_identifier_type_code_8 text, -- "Other Provider Identifier Type Code_8"
    other_provider_identifier_state_8 text, -- "Other Provider Identifier State_8"
    other_provider_identifier_issuer_8 text, -- "Other Provider Identifier Issuer_8"
    other_provider_identifier_9 text, -- "Other Provider Identifier_9"
    other_provider_identifier_type_code_9 text, -- "Other Provider Identifier Type Code_9"
    other_provider_identifier_state_9 text, -- "Other Provider Identifier State_9"
    other_provider_identifier_issuer_9 text, -- "Other Provider Identifier Issuer_9"
    other_provider_identifier_10 text, -- "Other Provider Identifier_10"
    other_provider_identifier_type_code_10 text, -- "Other Provider Identifier Type Code_10"
    other_provider_identifier_state_10 text, -- "Other Provider Identifier State_10"
    other_provider_identifier_issuer_10 text, -- "Other Provider Identifier Issuer_10"
    other_provider_identifier_11 text, -- "Other Provider Identifier_11"
    other_provider_identifier_type_code_11 text, -- "Other Provider Identifier Type Code_11"
    other_provider_identifier_state_11 text, -- "Other Provider Identifier State_11"
    other_provider_identifier_issuer_11 text, -- "Other Provider Identifier Issuer_11"
    other_provider_identifier_12 text, -- "Other Provider Identifier_12"
    other_provider_identifier_type_code_12 text, -- "Other Provider Identifier Type Code_12"
    other_provider_identifier_state_12 text, -- "Other Provider Identifier State_12"
    other_provider_identifier_issuer_12 text, -- "Other Provider Identifier Issuer_12"
    other_provider_identifier_13 text, -- "Other Provider Identifier_13"
    other_provider_identifier_type_code_13 text, -- "Other Provider Identifier Type Code_13"
    other_provider_identifier_state_13 text, -- "Other Provider Identifier State_13"
    other_provider_identifier_issuer_13 text, -- "Other Provider Identifier Issuer_13"
    other_provider_identifier_14 text, -- "Other Provider Identifier_14"
    other_provider_identifier_type_code_14 text, -- "Other Provider Identifier Type Code_14"
    other_provider_identifier_state_14 text, -- "Other Provider Identifier State_14"
    other_provider_identifier_issuer_14 text, -- "Other Provider Identifier Issuer_14"
    other_provider_identifier_15 text, -- "Other Provider Identifier_15"
    other_provider_identifier_type_code_15 text, -- "Other Provider Identifier Type Code_15"
    other_provider_identifier_state_15 text, -- "Other Provider Identifier State_15"
    other_provider_identifier_issuer_15 text, -- "Other Provider Identifier Issuer_15"
    other_provider_identifier_16 text, -- "Other Provider Identifier_16"
    other_provider_identifier_type_code_16 text, -- "Other Provider Identifier Type Code_16"
    other_provider_identifier_state_16 text, -- "Other Provider Identifier State_16"
    other_provider_identifier_issuer_16 text, -- "Other Provider Identifier Issuer_16"
    other_provider_identifier_17 text, -- "Other Provider Identifier_17"
    other_provider_identifier_type_code_17 text, -- "Other Provider Identifier Type Code_17"
    other_provider_identifier_state_17 text, -- "Other Provider Identifier State_17"
    other_provider_identifier_issuer_17 text, -- "Other Provider Identifier Issuer_17"
    other_provider_identifier_18 text, -- "Other Provider Identifier_18"
    other_provider_identifier_type_code_18 text, -- "Other Provider Identifier Type Code_18"
    other_provider_identifier_state_18 text, -- "Other Provider Identifier State_18"
    other_provider_identifier_issuer_18 text, -- "Other Provider Identifier Issuer_18"
    other_provider_identifier_19 text, -- "Other Provider Identifier_19"
    other_provider_identifier_type_code_19 text, -- "Other Provider Identifier Type Code_19"
    other_provider_identifier_state_19 text, -- "Other Provider Identifier State_19"
    other_provider_identifier_issuer_19 text, -- "Other Provider Identifier Issuer_19"
    other_provider_identifier_20 text, -- "Other Provider Identifier_20"
    other_provider_identifier_type_code_20 text, -- "Other Provider Identifier Type Code_20"
    other_provider_identifier_state_20 text, -- "Other Provider Identifier State_20"
    other_provider_identifier_issuer_20 text, -- "Other Provider Identifier Issuer_20"
    other_provider_identifier_21 text, -- "Other Provider Identifier_21"
    other_provider_identifier_type_code_21 text, -- "Other Provider Identifier Type Code_21"
    other_provider_identifier_state_21 text, -- "Other Provider Identifier State_21"
    other_provider_identifier_issuer_21 text, -- "Other Provider Identifier Issuer_21"
    other_provider_identifier_22 text, -- "Other Provider Identifier_22"
    other_provider_identifier_type_code_22 text, -- "Other Provider Identifier Type Code_22"
    other_provider_identifier_state_22 text, -- "Other Provider Identifier State_22"
    other_provider_identifier_issuer_22 text, -- "Other Provider Identifier Issuer_22"
    other_provider_identifier_23 text, -- "Other Provider Identifier_23"
    other_provider_identifier_type_code_23 text, -- "Other Provider Identifier Type Code_23"
    other_provider_identifier_state_23 text, -- "Other Provider Identifier State_23"
    other_provider_identifier_issuer_23 text, -- "Other Provider Identifier Issuer_23"
    other_provider_identifier_24 text, -- "Other Provider Identifier_24"
    other_provider_identifier_type_code_24 text, -- "Other Provider Identifier Type Code_24"
    other_provider_identifier_state_24 text, -- "Other Provider Identifier State_24"
    other_provider_identifier_issuer_24 text, -- "Other Provider Identifier Issuer_24"
    other_provider_identifier_25 text, -- "Other Provider Identifier_25"
    other_provider_identifier_type_code_25 text, -- "Other Provider Identifier Type Code_25"
    other_provider_identifier_state_25 text, -- "Other Provider Identifier State_25"
    other_provider_identifier_issuer_25 text, -- "Other Provider Identifier Issuer_25"
    other_provider_identifier_26 text, -- "Other Provider Identifier_26"
    other_provider_identifier_type_code_26 text, -- "Other Provider Identifier Type Code_26"
    other_provider_identifier_state_26 text, -- "Other Provider Identifier State_26"
    other_provider_identifier_issuer_26 text, -- "Other Provider Identifier Issuer_26"
    other_provider_identifier_27 text, -- "Other Provider Identifier_27"
    other_provider_identifier_type_code_27 text, -- "Other Provider Identifier Type Code_27"
    other_provider_identifier_state_27 text, -- "Other Provider Identifier State_27"
    other_provider_identifier_issuer_27 text, -- "Other Provider Identifier Issuer_27"
    other_provider_identifier_28 text, -- "Other Provider Identifier_28"
    other_provider_identifier_type_code_28 text, -- "Other Provider Identifier Type Code_28"
    other_provider_identifier_state_28 text, -- "Other Provider Identifier State_28"
    other_provider_identifier_issuer_28 text, -- "Other Provider Identifier Issuer_28"
    other_provider_identifier_29 text, -- "Other Provider Identifier_29"
    other_provider_identifier_type_code_29 text, -- "Other Provider Identifier Type Code_29"
    other_provider_identifier_state_29 text, -- "Other Provider Identifier State_29"
    other_provider_identifier_issuer_29 text, -- "Other Provider Identifier Issuer_29"
    other_provider_identifier_30 text, -- "Other Provider Identifier_30"
    other_provider_identifier_type_code_30 text, -- "Other Provider Identifier Type Code_30"
    other_provider_identifier_state_30 text, -- "Other Provider Identifier State_30"
    other_provider_identifier_issuer_30 text, -- "Other Provider Identifier Issuer_30"
    other_provider_identifier_31 text, -- "Other Provider Identifier_31"
    other_provider_identifier_type_code_31 text, -- "Other Provider Identifier Type Code_31"
    other_provider_identifier_state_31 text, -- "Other Provider Identifier State_31"
    other_provider_identifier_issuer_31 text, -- "Other Provider Identifier Issuer_31"
    other_provider_identifier_32 text, -- "Other Provider Identifier_32"
    other_provider_identifier_type_code_32 text, -- "Other Provider Identifier Type Code_32"
    other_provider_identifier_state_32 text, -- "Other Provider Identifier State_32"
    other_provider_identifier_issuer_32 text, -- "Other Provider Identifier Issuer_32"
    other_provider_identifier_33 text, -- "Other Provider Identifier_33"
    other_provider_identifier_type_code_33 text, -- "Other Provider Identifier Type Code_33"
    other_provider_identifier_state_33 text, -- "Other Provider Identifier State_33"
    other_provider_identifier_issuer_33 text, -- "Other Provider Identifier Issuer_33"
    other_provider_identifier_34 text, -- "Other Provider Identifier_34"
    other_provider_identifier_type_code_34 text, -- "Other Provider Identifier Type Code_34"
    other_provider_identifier_state_34 text, -- "Other Provider Identifier State_34"
    other_provider_identifier_issuer_34 text, -- "Other Provider Identifier Issuer_34"
    other_provider_identifier_35 text, -- "Other Provider Identifier_35"
    other_provider_identifier_type_code_35 text, -- "Other Provider Identifier Type Code_35"
    other_provider_identifier_state_35 text, -- "Other Provider Identifier State_35"
    other_provider_identifier_issuer_35 text, -- "Other Provider Identifier Issuer_35"
    other_provider_identifier_36 text, -- "Other Provider Identifier_36"
    other_provider_identifier_type_code_36 text, -- "Other Provider Identifier Type Code_36"
    other_provider_identifier_state_36 text, -- "Other Provider Identifier State_36"
    other_provider_identifier_issuer_36 text, -- "Other Provider Identifier Issuer_36"
    other_provider_identifier_37 text, -- "Other Provider Identifier_37"
    other_provider_identifier_type_code_37 text, -- "Other Provider Identifier Type Code_37"
    other_provider_identifier_state_37 text, -- "Other Provider Identifier State_37"
    other_provider_identifier_issuer_37 text, -- "Other Provider Identifier Issuer_37"
    other_provider_identifier_38 text, -- "Other Provider Identifier_38"
    other_provider_identifier_type_code_38 text, -- "Other Provider Identifier Type Code_38"
    other_provider_identifier_state_38 text, -- "Other Provider Identifier State_38"
    other_provider_identifier_issuer_38 text, -- "Other Provider Identifier Issuer_38"
    other_provider_identifier_39 text, -- "Other Provider Identifier_39"
    other_provider_identifier_type_code_39 text, -- "Other Provider Identifier Type Code_39"
    other_provider_identifier_state_39 text, -- "Other Provider Identifier State_39"
    other_provider_identifier_issuer_39 text, -- "Other Provider Identifier Issuer_39"
    other_provider_identifier_40 text, -- "Other Provider Identifier_40"
    other_provider_identifier_type_code_40 text, -- "Other Provider Identifier Type Code_40"
    other_provider_identifier_state_40 text, -- "Other Provider Identifier State_40"
    other_provider_identifier_issuer_40 text, -- "Other Provider Identifier Issuer_40"
    other_provider_identifier_41 text, -- "Other Provider Identifier_41"
    other_provider_identifier_type_code_41 text, -- "Other Provider Identifier Type Code_41"
    other_provider_identifier_state_41 text, -- "Other Provider Identifier State_41"
    other_provider_identifier_issuer_41 text, -- "Other Provider Identifier Issuer_41"
    other_provider_identifier_42 text, -- "Other Provider Identifier_42"
    other_provider_identifier_type_code_42 text, -- "Other Provider Identifier Type Code_42"
    other_provider_identifier_state_42 text, -- "Other Provider Identifier State_42"
    other_provider_identifier_issuer_42 text, -- "Other Provider Identifier Issuer_42"
    other_provider_identifier_43 text, -- "Other Provider Identifier_43"
    other_provider_identifier_type_code_43 text, -- "Other Provider Identifier Type Code_43"
    other_provider_identifier_state_43 text, -- "Other Provider Identifier State_43"
    other_provider_identifier_issuer_43 text, -- "Other Provider Identifier Issuer_43"
    other_provider_identifier_44 text, -- "Other Provider Identifier_44"
    other_provider_identifier_type_code_44 text, -- "Other Provider Identifier Type Code_44"
    other_provider_identifier_state_44 text, -- "Other Provider Identifier State_44"
    other_provider_identifier_issuer_44 text, -- "Other Provider Identifier Issuer_44"
    other_provider_identifier_45 text, -- "Other Provider Identifier_45"
    other_provider_identifier_type_code_45 text, -- "Other Provider Identifier Type Code_45"
    other_provider_identifier_state_45 text, -- "Other Provider Identifier State_45"
    other_provider_identifier_issuer_45 text, -- "Other Provider Identifier Issuer_45"
    other_provider_identifier_46 text, -- "Other Provider Identifier_46"
    other_provider_identifier_type_code_46 text, -- "Other Provider Identifier Type Code_46"
    other_provider_identifier_state_46 text, -- "Other Provider Identifier State_46"
    other_provider_identifier_issuer_46 text, -- "Other Provider Identifier Issuer_46"
    other_provider_identifier_47 text, -- "Other Provider Identifier_47"
    other_provider_identifier_type_code_47 text, -- "Other Provider Identifier Type Code_47"
    other_provider_identifier_state_47 text, -- "Other Provider Identifier State_47"
    other_provider_identifier_issuer_47 text, -- "Other Provider Identifier Issuer_47"
    other_provider_identifier_48 text, -- "Other Provider Identifier_48"
    other_provider_identifier_type_code_48 text, -- "Other Provider Identifier Type Code_48"
    other_provider_identifier_state_48 text, -- "Other Provider Identifier State_48"
    other_provider_identifier_issuer_48 text, -- "Other Provider Identifier Issuer_48"
    other_provider_identifier_49 text, -- "Other Provider Identifier_49"
    other_provider_identifier_type_code_49 text, -- "Other Provider Identifier Type Code_49"
    other_provider_identifier_state_49 text, -- "Other Provider Identifier State_49"
    other_provider_identifier_issuer_49 text, -- "Other Provider Identifier Issuer_49"
    other_provider_identifier_50 text, -- "Other Provider Identifier_50"
    other_provider_identifier_type_code_50 text, -- "Other Provider Identifier Type Code_50"
    other_provider_identifier_state_50 text, -- "Other Provider Identifier State_50"
    other_provider_identifier_issuer_50 text, -- "Other Provider Identifier Issuer_50"
    is_sole_proprietor text, -- "Is Sole Proprietor"
    is_organization_subpart text, -- "Is Organization Subpart"
    parent_organization_lbn text, -- "Parent Organization LBN"
    parent_organization_tin text, -- "Parent Organization TIN"
    authorized_official_name_prefix_text text, -- "Authorized Official Name Prefix Text"
    authorized_official_name_suffix_text text, -- "Authorized Official Name Suffix Text"
    authorized_official_credential_text text, -- "Authorized Official Credential Text"
    healthcare_provider_taxonomy_group_1 text, -- "Healthcare Provider Taxonomy Group_1"
    healthcare_provider_taxonomy_group_2 text, -- "Healthcare Provider Taxonomy Group_2"
    healthcare_provider_taxonomy_group_3 text, -- "Healthcare Provider Taxonomy Group_3"
    healthcare_provider_taxonomy_group_4 text, -- "Healthcare Provider Taxonomy Group_4"
    healthcare_provider_taxonomy_group_5 text, -- "Healthcare Provider Taxonomy Group_5"
    healthcare_provider_taxonomy_group_6 text, -- "Healthcare Provider Taxonomy Group_6"
    healthcare_provider_taxonomy_group_7 text, -- "Healthcare Provider Taxonomy Group_7"
    healthcare_provider_taxonomy_group_8 text, -- "Healthcare Provider Taxonomy Group_8"
    healthcare_provider_taxonomy_group_9 text, -- "Healthcare Provider Taxonomy Group_9"
    healthcare_provider_taxonomy_group_10 text, -- "Healthcare Provider Taxonomy Group_10"
    healthcare_provider_taxonomy_group_11 text, -- "Healthcare Provider Taxonomy Group_11"
    healthcare_provider_taxonomy_group_12 text, -- "Healthcare Provider Taxonomy Group_12"
    healthcare_provider_taxonomy_group_13 text, -- "Healthcare Provider Taxonomy Group_13"
    healthcare_provider_taxonomy_group_14 text, -- "Healthcare Provider Taxonomy Group_14"
    healthcare_provider_taxonomy_group_15 text, -- "Healthcare Provider Taxonomy Group_15"
    certification_date text -- "Certification Date"
);
create index if not exists ix_stg_nppes_npidata_npi on nppes.stg_nppes_npidata (npi);

drop table if exists nppes.stg_nppes_practice_location;
create table nppes.stg_nppes_practice_location (
    npi text, -- "NPI"
    provider_secondary_practice_location_address_address_line_1 text, -- "Provider Secondary Practice Location Address- Address Line 1"
    provider_secondary_practice_location_address_address_line_2 text, -- "Provider Secondary Practice Location Address-  Address Line 2"
    provider_secondary_practice_location_address_city_name text, -- "Provider Secondary Practice Location Address - City Name"
    provider_secondary_practice_location_address_state_name text, -- "Provider Secondary Practice Location Address - State Name"
    provider_secondary_practice_location_address_postal_code text, -- "Provider Secondary Practice Location Address - Postal Code"
    provider_secondary_practice_location_address_country_code_if_outside_u_s text, -- "Provider Secondary Practice Location Address - Country Code (If outside U.S.)"
    provider_secondary_practice_location_address_telephone_number text, -- "Provider Secondary Practice Location Address - Telephone Number"
    provider_secondary_practice_location_address_telephone_extension text, -- "Provider Secondary Practice Location Address - Telephone Extension"
    provider_practice_location_address_fax_number text -- "Provider Practice Location Address - Fax Number"
);
create index if not exists ix_stg_nppes_practice_location_npi on nppes.stg_nppes_practice_location (npi);

drop table if exists nppes.stg_nppes_othername;
create table nppes.stg_nppes_othername (
    npi text, -- "NPI"
    provider_other_organization_name text, -- "Provider Other Organization Name"
    provider_other_organization_name_type_code text -- "Provider Other Organization Name Type Code"
);
create index if not exists ix_stg_nppes_othername_npi on nppes.stg_nppes_othername (npi);

drop table if exists nppes.stg_nppes_endpoint;
create table nppes.stg_nppes_endpoint (
    npi text, -- "NPI"
    endpoint_type text, -- "Endpoint Type"
    endpoint_type_description text, -- "Endpoint Type Description"
    endpoint text, -- "Endpoint"
    affiliation text, -- "Affiliation"
    endpoint_description text, -- "Endpoint Description"
    affiliation_legal_business_name text, -- "Affiliation Legal Business Name"
    use_code text, -- "Use Code"
    use_description text, -- "Use Description"
    other_use_description text, -- "Other Use Description"
    content_type text, -- "Content Type"
    content_description text, -- "Content Description"
    other_content_description text, -- "Other Content Description"
    affiliation_address_line_one text, -- "Affiliation Address Line One"
    affiliation_address_line_two text, -- "Affiliation Address Line Two"
    affiliation_address_city text, -- "Affiliation Address City"
    affiliation_address_state text, -- "Affiliation Address State"
    affiliation_address_country text, -- "Affiliation Address Country"
    affiliation_address_postal_code text -- "Affiliation Address Postal Code"
);
create index if not exists ix_stg_nppes_endpoint_npi on nppes.stg_nppes_endpoint (npi);

